/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBondCalculator,
  IBondCalculatorInterface,
} from "../IBondCalculator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_LP",
        type: "address",
      },
    ],
    name: "markdown",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_LP",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "valuation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBondCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): IBondCalculatorInterface {
    return new utils.Interface(_abi) as IBondCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBondCalculator {
    return new Contract(address, _abi, signerOrProvider) as IBondCalculator;
  }
}
